### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by John3** [gentee/gentee#2]
Hey Alexey 

great project :) by change you can add a few examples in the documentation? that anyone just can run easy like ./gentee example1.g and see a full script with gentee?

I'm wrong or this is not related to this project? https://www.gentee.com/programming/samples/

**Comment by gentee** [comment]
Hi,
www.gentee.com is the old project of another programming laguage with the same name. I am going to close it later. 
At this moment, there is not an example area, but I think I will add some examples. Anybody may send ideas for examples.
Now you look at gentee sources in tests/*_test and tests/stdlib/*_test files. Each test file contains some small scripts for testing purpose.

**Comment by gentee** [comment]
I have added examples folder with Gentee examples.
