### ISSUE TITLE
Conversion between Gentee types and Golang types

### ISSUE THREAD

**Issue by lsascha** [gentee/gentee#4]
Is there any example, or already included easy way to convert between Golang and Gentee types?

For example to convert between a Golang Map to a Gentee Map, i made the following function:
```golang
func GoMap2GenteeMap(goMap map[string]interface{}) *core.Map {
	ret := core.NewMap()
	for key, _ := range goMap {
		ret.Keys = append(ret.Keys, key)
	}
	ret.Data = goMap
	return ret
}
```

But i have the feeling as if i am missing something.

Sorry if it is obvious, but i am still relatively new to Golang.

**Comment by gentee** [comment]
Yes, I think it should work.
But goMap must have the items of the same types.
For example,
int64 -> int gentee type
string -> str gentee type
float64 -> float gentee type
etc.
Otherwise, Gentee wouldn't be able to work with the converted map.

**Comment by lsascha** [comment]
thanks.
Yes i tested that function and it works in my case.

My Question was more like if there is any already included easier way to convert between gentee and golang types.
Just that i was not able to find it with looking through the code or looking into the documentation.

If not, i guess it would be a nice feature suggestion?

But thanks anyway.
And thanks for making this nicely working scripting language for go.

**Comment by gentee** [comment]
What functions would you like to suggest? 
go map -> gentee map
go slice -> gentee arr
go struct -> gentee struct ?
In this case, converting function must know the result Gentee type.
For example,
If we convert go map to gentee map the function must looks like
Prototype:
GoMap2Map(in map[string]interface{}, result string) (*core.Map, error)
Example:
result, err := GoMap2Map(mymap, "map.int")
result, err := GoMap2Map(mymap, "map.arr.mytype")
It will make the safe conversion or throw an error if the go source parameter is not compatible with the result type.

**Comment by lsascha** [comment]
yes. i think that would be a solution.

For example i execute a gentee script and wanted to process the resulting string array further in golang.

I ended up making this methods:
```go
func GenteeTypeToGolangInterface(genteeInterface interface{}) interface{} {
	var returnArray interface{}
	switch v := genteeInterface.(type) {
	case *core.Array:
		returnArray = v.Data
	}
	return returnArray
}
func InterfaceToStringArr(golangInterface interface{}) []string {
	tmpInterface := golangInterface.([]interface{})
	s := make([]string, len(tmpInterface))
	for i, v := range tmpInterface {
		s[i] = v.(string)
	}
	return s
}
// ...
goArray := InterfaceToStringArr(GenteeTypeToGolangInterface(scriptReturn))
```

and there are many more cases where i had wished it would be easy to just convert from one type to another.

at least the function to convert the gentee bool to the golang boolean was relatively simple.
```go
func GenteeTypeInt64ToBool(integer int64) bool {
	if integer >= 1 {
		return true
	}
	return false
}
```

i guess the names should be different, or make a more general function that can convert between all types like you suggested like
```go
result, err := GoType2GenteeType(goType, "arr.str")
```
and
```go
result, err := GenteeType2GoType(genteeType)
/* (do we really need to tell it the target type
 or can we convert it automatically based on the provided variable?) */
```

**Comment by gentee** [comment]
Well. I will try to realize something like that this week.

**Comment by gentee** [comment]
I have just add Go@GenteeType & Gentee2GoType functions.
Documentation is available on https://docs.gentee.org/golang/reference
Test examples can be found in tests/custom_test.go
You can define your own conversion fucntions by using these two ones.

**Comment by lsascha** [comment]
Sorry for the silence.
Just got to test it, and seems to work perfectly fine. :) Thanks.

**Comment by lsascha** [comment]
Sorry. i think i was a bit too early to close it.

I am getting this error when i try to convert a arr.str to a golang string array.
so this line `goArray := Gentee2GoType(genteeArray).([]string)`
results in this error at runtime.
`panic: interface conversion: interface {} is []interface {}, not []string`

**Comment by gentee** [comment]
By default, any arr is converted to []interface{} and any map to map[string]interface{}. I have done this because it is impossible to  predefine all possible cases. So, you should use it like this
```
for i, item := range Gentee2GoType(genteeArray) {
      fmt.Println(i, item.(string) )
}
```

**Comment by lsascha** [comment]
ah. now i understand the table in the documentation. :see_no_evil: 
i was wondering about the `Result type (vtype)` column.

Sorry about that. Now it works. :)
