### ISSUE TITLE
Ctrl+Esc to stop running scripts does not work on W10 PC

### ISSUE THREAD

**Issue by raisinc** [gentee/gentee#5]
In Windows 10 pressing Ctrl+Esc in "Perfect Automation" project's executable (hidden) causes the Start Menu to activate, so I am unable to cancel execution of a macro.  Is there a way to alter the "Stop Execution"Key combination?

**Comment by gentee** [comment]
Unfortunately, there is not a way to redefine this key combination. We stopped supporting and developing Perfect Automation many years ago. It is distributed as is.

**Comment by raisinc** [comment]
OK, thanks for answering my query.
